### ISSUE TITLE
Ask Astro || Noticed sometimes response time take more than 15s

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/ask-astro#119] opened 2023-11-14 08:29 UTC
Noticed sometimes response time take more than 15s

**Comment by pankajastro** [comment] 2023-12-17 11:10
looks duplicate of https://github.com/astronomer/ask-astro/issues/13

**Comment by davidgxue** [comment] 2024-03-06 19:37
closing this issue as it is a duplicate of #13

**Closed by davidgxue** 2024-03-06 19:37 UTC
